// src/ui/vue/src/components/package-view.vue
<template>
  <div id="package-view">
    <package-list />
    <!-- router-view / -->
  </div>
</template>

<script>
import PackageList from './package/list'

export default {
  name: 'package-view',
  components: { PackageList }
}
</script>

<style scoped>
#package-view {
  padding: 25px 25px 25px 45px;
}
</style>

// src/ui/react-ui/src/components/package/package-view.js
import React from 'react';
import {
  BrowserRouter as Router, 
  Switch, 
  Route
} from 'react-router-dom';
import PackageInfo from './package-info'

import PackageList from './package-list'

export default function PackageView() {
  return (
    <Router>
      <div className="PackageView">
        <Switch>
          <Route exact path="/">
            <PackageList />
          </Route>
          <Route exact path="/package/:name" component={ PackageInfo } />
        </Switch>
      </div>
    </Router>
  );
}
